name 'formatron_sensu'
version '0.1.1'
description 'Formatron Sensu cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/sensu-cookbook'
issues_url 'https://github.com/formatron/sensu-cookbook/issues'
supports 'ubuntu'
depends 'apt'
