name 'formatron_sensu'
version '0.1.0'
description 'Formatron Sensu cookbook'
source_url 'https://github.com/formatron/sensu-cookbook'
issues_url 'https://github.com/formatron/sensu-cookbook/issues'
supports 'ubuntu'
depends 'apt'
